// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.Persistence;

#nullable disable

namespace Restaurant.Persistence.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250419043604_SavedAddresses")]
    partial class SavedAddresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryDish", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "DishesId");

                    b.HasIndex("DishesId");

                    b.ToTable("CategoryDish");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.CartDishItem", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("CartId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Entities", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderDishItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Verification", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<bool>("CanLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("CheckId")
                        .HasColumnType("text");

                    b.HasKey("Number");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Verifications", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cart", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Category", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dish", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<bool>("AddChopsticks")
                        .HasColumnType("boolean");

                    b.Property<bool>("AddForks")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float?>("DeliveryCost")
                        .HasColumnType("real");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PersonQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceiptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiptMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Promotion", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdvanced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.SavedAddress", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("SavedAddresses", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.User", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.Entity");

                    b.Property<Guid?>("DefaultAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.User");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("Restaurant.Domain.Entities.User");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("CategoryDish", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.CartDishItem", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Entity", b =>
                {
                    b.OwnsOne("Restaurant.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderDishItem", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Verification", b =>
                {
                    b.OwnsOne("Restaurant.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<string>("VerificationNumber")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VerificationNumber");

                            b1.ToTable("Verifications");

                            b1.WithOwner()
                                .HasForeignKey("VerificationNumber");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Cart", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Restaurant.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Category", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Restaurant.Domain.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPublished")
                                .HasColumnType("boolean");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dish", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Dish", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Restaurant.Domain.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("DishId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPublished")
                                .HasColumnType("boolean");

                            b1.HasKey("DishId");

                            b1.ToTable("Dishes");

                            b1.WithOwner()
                                .HasForeignKey("DishId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Order", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Restaurant.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Entrance")
                                .HasColumnType("text");

                            b1.Property<int>("Floor")
                                .HasColumnType("integer");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Promotion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Restaurant.Domain.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPublished")
                                .HasColumnType("boolean");

                            b1.HasKey("PromotionId");

                            b1.ToTable("Promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.SavedAddress", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.SavedAddress", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.User", "User")
                        .WithMany("SavedAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Restaurant.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SavedAddressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Entrance")
                                .HasColumnType("text");

                            b1.Property<int>("Floor")
                                .HasColumnType("integer");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SavedAddressId");

                            b1.ToTable("SavedAddresses");

                            b1.WithOwner()
                                .HasForeignKey("SavedAddressId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.User", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Restaurant.Domain.Entities.FncToken", "FncTokens", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("FncToken");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId");

                            b1.Navigation("User");
                        });

                    b.OwnsOne("Restaurant.Domain.Entities.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("FncTokens");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Client", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Domain.Entities.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("SavedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
