<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="uploads\**" />
    <Content Remove="uploads\**" />
    <EmbeddedResource Remove="uploads\**" />
    <None Remove="uploads\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Application\Restaurant.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Persistence\Restaurant.Persistence.csproj" />
    <ProjectReference Include="..\Restaurant.Security\Restaurant.Security.csproj" />
    <ProjectReference Include="..\Restaurant.Services\Restaurant.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middleware\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
  </ItemGroup>

</Project>
